# Generated by Django 4.1.3 on 2023-03-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('color_hash', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('latitude', models.FloatField(default=0.0, max_length=12)),
                ('longitude', models.FloatField(default=0.0, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='RouteWithStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybs_transport.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybs_transport.stop')),
            ],
            options={
                'db_table': 'ybs_route_with_stop',
            },
        ),
        migrations.CreateModel(
            name='BusWithRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybs_transport.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybs_transport.route')),
            ],
            options={
                'db_table': 'ybs_bus_with_route',
            },
        ),
    ]
